# Generated by Django 3.0.8 on 2020-07-30 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=70, null=True)),
                ('last_name', models.CharField(blank=True, max_length=70, null=True)),
                ('id_number', models.IntegerField(blank=True)),
                ('data_of_employment', models.DateTimeField()),
                ('gender', models.CharField(blank=True, max_length=70)),
                ('department', models.CharField(blank=True, max_length=70)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile/')),
                ('phone_number', models.CharField(blank=True, max_length=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.TextField(choices=[('approved', 'approved'), ('declined', 'declined')], max_length=10)),
                ('leave_app', models.TextField(blank=True, choices=[('annual', 'annual'), ('sick', 'sick'), ('maternity', 'maternity'), ('paternity', 'paternity'), ('compassionate', 'compassionate'), ('study', 'study'), ('unpaid', 'unpaid')], max_length=20, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_app.Employee')),
            ],
        ),
    ]
