# Generated by Django 3.0.8 on 2020-07-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='date_applied',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='job_title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
