# Generated by Django 3.0.8 on 2020-07-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0003_auto_20200730_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='employee_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
    ]
