# Generated by Django 3.0.8 on 2020-07-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0004_auto_20200730_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='data_of_employment',
            new_name='date_of_employment',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_name',
        ),
    ]
