# Generated by Django 3.0.8 on 2020-08-03 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0008_auto_20200730_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced'), ('entanglement', 'entanglement')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_app',
            field=models.TextField(blank=True, choices=[('annual', 'annual'), ('sick', 'sick'), ('maternity', 'maternity'), ('paternity', 'paternity'), ('compassionate', 'compassionate')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Next_of_kin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=20)),
                ('dials', models.CharField(blank=True, max_length=70)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('address', models.CharField(blank=True, max_length=70)),
                ('relation', models.CharField(blank=True, max_length=70)),
                ('kin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leave_app.Employee')),
            ],
        ),
    ]
