# Generated by Django 3.0.8 on 2020-08-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0009_auto_20200803_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='job_title',
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Entanglement', 'Entanglement')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_app',
            field=models.TextField(blank=True, choices=[('Annual', 'Annual'), ('Sick', 'Sick'), ('Maternity', 'Maternity'), ('Paternity', 'Paternity'), ('Compassionate', 'Compassionate')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.TextField(choices=[('Approved', 'Approved'), ('Declined', 'Declined')], max_length=10),
        ),
    ]
