# Generated by Django 3.0.8 on 2020-08-03 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0011_auto_20200803_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.TextField(choices=[('Approved', 'Approved'), ('Declined', 'Declined'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='next_of_kin',
            name='kin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_app.Employee'),
        ),
    ]
